/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    invoices: Invoice;
    payments: Payment;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    'quick-access': QuickAccessWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  phone?: string | null;
  /**
   * Appears on invoices as the sender business name.
   */
  businessName?: string | null;
  /**
   * Your business tax identification number. Appears on invoices.
   */
  taxId?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    country?: ('US' | 'GB' | 'CA' | 'AU' | 'IN' | 'DE' | 'FR' | 'JP' | 'BR' | 'OTHER') | null;
  };
  company?: string | null;
  /**
   * User role. Only admins can modify this.
   */
  role: 'user' | 'admin';
  /**
   * Your business logo. Appears on invoices and payment pages. Max 2MB, JPG/PNG only.
   */
  logo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  client: {
    name: string;
    email: string;
    phone?: string | null;
    address?: string | null;
    taxId?: string | null;
  };
  lineItems: {
    description: string;
    quantity: number;
    unitPrice: number;
    /**
     * Auto-calculated: quantity × unitPrice
     */
    amount?: number | null;
    id?: string | null;
  }[];
  /**
   * Auto-calculated: sum of all line item amounts
   */
  subtotal?: number | null;
  taxRate?: number | null;
  taxLabel?: string | null;
  /**
   * Auto-calculated from tax rate
   */
  taxAmount?: number | null;
  discountType?: ('percentage' | 'fixed') | null;
  discountValue?: number | null;
  /**
   * Auto-calculated from discount type and value
   */
  discountAmount?: number | null;
  /**
   * Auto-calculated: subtotal - discount + tax
   */
  total?: number | null;
  currency:
    | 'USD'
    | 'EUR'
    | 'GBP'
    | 'INR'
    | 'CAD'
    | 'AUD'
    | 'JPY'
    | 'BRL'
    | 'MXN'
    | 'SGD'
    | 'CHF'
    | 'SEK'
    | 'NOK'
    | 'DKK'
    | 'NZD'
    | 'ZAR'
    | 'HKD'
    | 'KRW'
    | 'CNY'
    | 'PLN';
  issueDate: string;
  dueDate: string;
  /**
   * Appears at the bottom of the invoice.
   */
  notes?: string | null;
  /**
   * Invoice lifecycle status.
   */
  status: 'draft' | 'sent' | 'viewed' | 'paid' | 'overdue' | 'cancelled' | 'refunded';
  /**
   * Auto-generated slug for the public payment page.
   */
  paymentLink?: string | null;
  /**
   * Set automatically when payment is received.
   */
  paidAt?: string | null;
  /**
   * Payment gateway used.
   */
  paidVia?: ('stripe' | 'paypal') | null;
  /**
   * Stripe payment intent ID for reconciliation.
   */
  stripePaymentIntentId?: string | null;
  /**
   * PayPal order ID for reconciliation.
   */
  paypalOrderId?: string | null;
  /**
   * Auto-generated: INV-YYYY-XXXX (per-user serialized).
   */
  invoiceNumber?: string | null;
  /**
   * Auto-set to the user who created this invoice.
   */
  owner: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  /**
   * The invoice this payment is for.
   */
  invoice: number | Invoice;
  gateway: 'stripe' | 'paypal';
  amount: number;
  /**
   * Matches the invoice currency.
   */
  currency: string;
  /**
   * Payment processing status.
   */
  status: 'pending' | 'succeeded' | 'failed' | 'refunded' | 'partially_refunded';
  /**
   * Stripe payment intent ID or PayPal order ID.
   */
  gatewayTransactionId: string;
  payerEmail?: string | null;
  payerName?: string | null;
  /**
   * Raw gateway response for debugging.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Unique key to prevent duplicate webhook processing.
   */
  idempotencyKey: string;
  /**
   * When the payment was processed by the gateway.
   */
  processedAt?: string | null;
  /**
   * When a refund was issued.
   */
  refundedAt?: string | null;
  /**
   * Partial or full refund amount.
   */
  refundAmount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action:
    | 'invoice.created'
    | 'invoice.updated'
    | 'invoice.sent'
    | 'invoice.paid'
    | 'invoice.cancelled'
    | 'payment.received'
    | 'payment.failed'
    | 'payment.refunded'
    | 'user.login'
    | 'user.logout'
    | 'user.updated';
  /**
   * Collection name: invoice, payment, or user.
   */
  entity: string;
  /**
   * ID of the affected record.
   */
  entityId: string;
  /**
   * Who performed the action. Null for webhook/system events.
   */
  user?: (number | null) | User;
  ipAddress?: string | null;
  userAgent?: string | null;
  /**
   * Snapshot of data before the change.
   */
  previousData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Snapshot of data after the change.
   */
  newData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  businessName?: T;
  taxId?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
      };
  company?: T;
  role?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  client?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        address?: T;
        taxId?: T;
      };
  lineItems?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        amount?: T;
        id?: T;
      };
  subtotal?: T;
  taxRate?: T;
  taxLabel?: T;
  taxAmount?: T;
  discountType?: T;
  discountValue?: T;
  discountAmount?: T;
  total?: T;
  currency?: T;
  issueDate?: T;
  dueDate?: T;
  notes?: T;
  status?: T;
  paymentLink?: T;
  paidAt?: T;
  paidVia?: T;
  stripePaymentIntentId?: T;
  paypalOrderId?: T;
  invoiceNumber?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  invoice?: T;
  gateway?: T;
  amount?: T;
  currency?: T;
  status?: T;
  gatewayTransactionId?: T;
  payerEmail?: T;
  payerName?: T;
  metadata?: T;
  idempotencyKey?: T;
  processedAt?: T;
  refundedAt?: T;
  refundAmount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  entity?: T;
  entityId?: T;
  user?: T;
  ipAddress?: T;
  userAgent?: T;
  previousData?: T;
  newData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quick-access_widget".
 */
export interface QuickAccessWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}